/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ombghdrotkprsckvcalp"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9tYmdoZHJvdGtwcnNja3ZjYWxwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxMTQ3NDgsImV4cCI6MjA3NzY5MDc0OH0.4h07-kq0sCIG_ydSh0-fZXSMUCtsLbDJ71731o7hzDY"